### ISSUE TITLE
Can Instrain differentiate between read_ids for paired-end file in bam file?

### ISSUE THREAD

**Issue by kaysahu** [MrOlm/inStrain#105]
Hi,

I have been running Instrain for over a year now and this is the first time I have come across this issue.

In the BAM file, do you think the QUERYID matters to identify the paired-end reads information? When I have paired-end reads named specifically with .1 and .2 in the read-id it looks like INSTRAIN will fail.

Here is the original BAM file for which INSTRAIN profile command worked perfectly:

![image](https://user-images.githubusercontent.com/53317454/171230246-fcf8a6f4-1bd7-432e-a832-c17e4ffe715b.png)

Next, here is the BAM file for which INSTRAIN failed:

![image](https://user-images.githubusercontent.com/53317454/171230510-ca77f679-7348-4b76-a0c4-ac2dfcbed90a.png)

As you can see, the difference between the highlighted portions in both images is simply related to the paired-end reads. The second image specifically mentions which paired-end file the original read belongs to (with .1 and .2 in their query names, some raw files will have /1 and/2) but in the first one, it does not.

Here is  the instrain error:

![image](https://user-images.githubusercontent.com/53317454/171231128-c7d763bd-897b-46ed-9c5f-ef954c83a363.png)

Do you already have a solution for this type of problem? Or do I need to manually make sure the paired-read IDs have the exact same query name in bam files before using INSTRAIN? Thank you.

**Comment by MrOlm** [comment]
Hi @kaysahu ,

Sorry you're encountering this problem but unfortunately yes, the way that inStrain detects paired reads is based on the reads having the same name.

If keeping the pair linkage information isn't important for your analysis you could run with the flag `--pairing_filter all_reads` and treat each end of the pair as a separate read, but otherwise you'll need to ensure that read pairs have the same name prior to running inStrain.

Best,
Matt
