### ISSUE TITLE
position in scaffold

### ISSUE THREAD

**Issue by guyuanl** [MrOlm/inStrain#110]
Hello,
I'm having some problems with using inStrain. For the SNVs.tsv output table, I tried to manually calculate the position of the SNP in the scaffold it is located in reference genome.For inStrain, the calculations are done as followed

inStrain reports 0-based values for “position”. The first base in a scaffold will be position “0”, second based position “1”, etc.

So,for example, a SNV at position 715 in scaffold N5_271_010G1_scaffold_0 (N5_271_010G1_scaffold_min1000.fa-vs-N5_271_010G1.IS_SNVs.tsv), it's "ref_base" should be the 716th base in the reference.(>N5_271_010G1_scaffold_0 read_length_150 read_count_399). But when the "ref_base" is "T" , there is  "A" on the 716th base in the reference scaffold. I found that many of the  "ref_base" on the SNVs table did not match the position in the reference scaffold, please correct me if I'm wrong, I'd very much like to learn.

I hope you could take a look at this issue.

Best wishes,
Liang

**Comment by MrOlm** [comment]
Hi Liang,

Thank you for reaching out. We've spent a good bit of time going through and making sure the RefBase and positions match up, but due to the 0-based counting this often does get confusing.

Can I ask what software you're using to identify the 716th base in a scaffold? And which file you're getting the scaffold from?

Thanks,
Matt

**Comment by guyuanl** [comment]
Hi Matt,

I rechecked it with IGV and the results were fine. Thank you for your help!

Best,
Liang
