### ISSUE TITLE
Minor issue with argument orders for inStrain profile

### ISSUE THREAD

**Issue by ryanmelnyk** [MrOlm/inStrain#114]
Hi Matt! I'm working on building some new pipelines and have found inStrain (and your readthedocs) very helpful and informative, especially for someone very new to metagenomics.

I found a minor issue with the order of arguments when running `inStrain profile`. I'm running v1.6.3 installed with conda.

I haven't fully debugged the issue as it seems to only occur when the last argument before the positional bam & fasta files is itself a path. E.g. the following command fails and yields an argparse error about requiring a bam and fasta.

```
inStrain profile \
  -p 16 \
  --skip_mm_profiling \
  --database_mode \
  -o ${prefix}_instrain_elgg \
  -g ${params.db_path}/${params.db_name}.genes.fna \
  -s ${params.db_path}/${params.db_name}.stb.tsv \
  ${input_bam} \
  ${params.db_path}/${params.db_name}.fna
```

A simple fix I found was to rearrange the order of the args 

```
inStrain profile \
    -p 16 \
    -o ${prefix}_instrain_elgg \
    -g ${params.db_path}/${params.db_name}.genes.fna \
    -s ${params.db_path}/${params.db_name}.stb.tsv \
    --skip_mm_profiling \
    --database_mode \
    ${input_bam} \
    ${params.db_path}/${params.db_name}.fna
```

PS Sorry for the nextflow syntax - params.db_path is an absolute path and params.db_name is just a string.

**Comment by MrOlm** [comment]
Hi Ryan- thanks for the kind words!

Yes this is a confusing thing with argparse- the issue is that the `-s` argument can take multiple arguments, so in the first example argparse thinks the bam file and the fasta file are part of the `-s` argument.

In the second example, the bam file and the fasta file are after a flag that accepts no arguments, so it knows to treat them as positional arguments.

A way of getting around this is to always have then bam file and the fasta file after the `profile` command (so they never get sucked up into another argument with multiple options), but obviously your second example works too. 

Let me know if you hit any other snags!
-Matt
