### ISSUE TITLE
Problem of false positive SNVs 

### ISSUE THREAD

**Issue by gabrieleghiotto** [MrOlm/inStrain#117]
Good morning,
I am a PhD student  at the university of Padova. During my master's thesis I used InStrain to call variants on metagenomics samples sequenced with Illumina. At the moment we were trying to understand how much reliable is the calling procedure that the software perform, especially regarding the number of false positives SNVs called with respect to the total. To test this aspect, we took a reference genome from NCBI of Lactobacilli and aligned the reads, finding around 1000 SNVs. Then, we re-assembled the genome with our reads, thinking that maybe there was an error on the genome deposited, but the result was about 800 SNVs. In theory the number of variants should be very low, so we assumed that this are all false positives. The question is, did you encounter this issue during the development of the software and there is some way to quantify the amount of false positive SNVs with respect to the total SNVs called? In addition, is there any procedure that can be applied to reduce the amount of false positives? Thanks in advance

Kind regards

**Comment by MrOlm** [comment]
Hi @gabrieleghiotto

Interesting question and thanks for reaching out.

There are lots of filters that inStrain uses to try and filter out SNVs, but in a metagenomic context, most of these SNVs that you're calling "false positives" are likely the result of mis-mapping. That is, reads from organisms that are not Lactobacilli are mapping to your Lactobacilli. Increasing the `--min_read_ani` to something like 0.98 or 0.99 can help with this, but it may resulting in missing some genuine SNVs.

I would encourage you to visualize the .bam file using a program like IGV at the position where some of these "false positive" SNVs are called to see what's going on. Often you can visually tell why such a position is being called as an SNV and understand what the problem is. If you do find any positions that indeed look like false positives after visualization like that, please let me know and I'd be happy to help troubleshoot.

Best,
Matt

**Comment by MrOlm** [comment]
`Samtools tview` and `tablet` are also good and easy to use visualization tools
