### ISSUE TITLE
Question about instrain

### ISSUE THREAD

**Issue by SilasK** [MrOlm/inStrain#120]
Hello, thank you very much for developing this robust and easy-to-use tool.

I'm analyzing ~400 Nasophyringal samples of children. I wanted to see if there are some strain transmissions between the same child at 2 month intervals and compare them to between children transmissions. 

I assembled genomes, dereplicated them at 95% ANI, and used the InSTrain with default parameters.

In the genome-wide table I see ~80 comparisons between samples of the same child at different timepoints when I could expect 150 x n species of those comparisons. I know the data is not perfect, there are probably many low abundant genomes in this samples for which inStrain doean't report a strain comparison. 

How can I see if this is really the case?
Would it make sense to tune some parameters? e.g. should I decrease the min_cov from 5 to 2? are there other parameters that I should change? 

The final `comparison_strain_clusters.tsv ` shows me that each sample has pretty much it's own strain for all genomes (except some contaminations).

**Comment by MrOlm** [comment]
Hi @SilasK -

I love your research question- how exciting!

If you look at the inStrain profile tables for each sample, you should be able to see which genomes are detected on a sample-by-genome level. With default settings, all genomes with `breadth_mincov` > 0.5 **should** be compared with inStrain compare. If that's not the case please let me know and we can troubleshoot

Unfortunately, for reliable results, there's not much that can be done about this. You could adjust settings to make it compare more things (as you suggest), but the results will likely be very noisy and not very accurate. Kind of the only thing to do would be to sequence deeper in order to increase `breadth_mincov`.

Please let me know if you have any other questions

-Matt

**Comment by SilasK** [comment]
Hello, thank you for your reply. I checked the `genome_info` file and the results make sense. I try with a lower breath. You would say not to reduce the min_cov for comparison?

**Comment by MrOlm** [comment]
Hi @SilasK -

I would not recommend lowing it for instrain 

I believe other callers work on the consensus ANI, not popANI, which doesn’t require as high of coverage. I do recognize that instrain requires pretty high coverage to work properly, and if your samples don’t have that, it could make sense to use another piece of software like the one you link to.

Best,
Matt

**Comment by SilasK** [comment]
Thank you for your response. I only wish strainGE would be as simple to use as inStrain
