### ISSUE TITLE
Can we use inStrain profile results (e.g. popANI, conANI) to decide if two genomes belong to the same strain?

### ISSUE THREAD

**Issue by JemmaSun** [MrOlm/inStrain#135]
Hi Matt,

I have two genomes (say genomes A and B) recovered from cultures inoculated from the same raw sample but under different cultivation conditions. Their ANI and AAI are all > 99%.  And I would like to use inStrain to provide more evidence to support that A and B are the same strain. 

I have generated a list of inStrain profiles using bam files from mapping metagenome reads of my samples against the **concatenated** fasta file of genomes A and B. The COMPARE function resulted in zero clusters regarding my input samples (which makes sense as they were under different cultivation conditions). Still, I would like to use the statistics in the `COMPARE_genomeWide_compare.tsv` table to show that genomes A and B are possibly from the same strain (e.g. by ). My questions are:

1) Can I decide if two genomes belong to the same strain by comparing if the coverage, popANI, conANI, etc. are different between these two genomes when mapping to the same set of sample pairs?

2) If 1) is true, when preparing for the profiles, should I concatenate the two genomes to obtain a single instrain profile (i.e.  sample1_genomeAB.profile, sample2_genomeAB.profile, etc.) per sample, or should I map the reads to A and B separately and get two instrain profiles per sample (i.e. sample1_genomeA.profile, sample1_genomeB.profile, sample2_genomeA.profile, sample2_genomeB.profile, etc.)? I am asking because, when I do it the former way,  I have seen the coverages in `COMPARE_genomeWide_compare.tsv` of genome A and B against the same sample pairs can be >10 times different in values; But given that the two genomes are nearly identical, we would expect their coverages also being similar.

Apologies for the long question above. Thank you in advance!

Kind regards,
Jiarui

**Comment by MrOlm** [comment]
Hi Jiarui,

Great questions- I'm happy to help sort this out.

In your scenario you almost definitely want to map to just one genome at a time because they're so similar. More info on why exactly this is the case, and why you're seeing the weird coverage values, can be found here - https://instrain.readthedocs.io/en/latest/important_concepts.html#a-ensure-that-genomes-are-distinct-from-one-another

You could run the same analysis twice (once mapped to genome A and once mapped to genome B), but given their similarity you will almost certainly see the same results for mapping to either genome.

You can find some advice on picking a popANI threshold to determine if strains are identical or not here - https://instrain.readthedocs.io/en/latest/important_concepts.html#thresholds-for-determining-same-vs-different-strains . I like to use a threshold of 99.999% popANI

Let me know if I didn't answer anything or if there are other questions you have!

Best,
Matt
