### ISSUE TITLE
pNpS calculations

### ISSUE THREAD

**Issue by Riiiiiis** [MrOlm/inStrain#137]
Hello! 

Is it correct, that pNpS values calculated in gene_info files is done by the following? :

[sum(SNV_N_count) / sum(N_sites)] / [[sum(SNV_S_count) / sum(S_sites)]

If so, where do i find the information on each gene's number of N sites / S sites?

Best

**Comment by MrOlm** [comment]
Hello,

Yes- that formula is correct. That information is in the file `genes_table` within the `raw_data` output folder. You'll see the columns `N_sites` and `S_sites` in that file.

Best,
Matt

**Comment by Riiiiiis** [comment]
Hi again, 
Thanks for the confirmation! 

From former yields of inStrain, the gene_info.tsv file contained columns:  SNV_S_count and SNV_N_count. Do these then correspond to S_sites and N_sites respectively?

Best, 
Kristian

**Comment by MrOlm** [comment]
Hi Kristian,

No, those are the number of N and S mutations. The number of sites is in the table in the raw_data folder.

Best,
Matt

**Comment by Riiiiiis** [comment]
I see, thanks Matt!

Best, 
Kristian

**Comment by haihao999** [comment]
Hi Matt,
I have a few confusing questions for you, firstly, are the pNpS_variants in the gene_info.tsv file pN/pS values, and if so, are the pN/pS values for the genome averaged over all the genes.，Or after calculating all gene sums from genes_SNP_count file and then dividing by？ Because I got a snvs_genome_summary file from the Rcode in the article(Microcoleus (Cyanobacteria) form watershed-wide populations without strong gradients in population structure), and there is a NS value in it (N_count/S_count) does it make sense? Because of this value I thought at first it was pN/pS values......
Best,
yanpeng

**Comment by MrOlm** [comment]
Hi yanpeng,

Descriptions of the various outputs can be found here:

https://instrain.readthedocs.io/en/latest/example_output.html#gene-info-tsv

I believe the NS value reported there is not Pn/pS, but just total number of non-synonymous / total number of synonymous.

Best,
Matt

**Comment by dzxiaona** [comment]
Hi Matt,

If the pNpS for the gene was calculated by [sum(SNV_N_count)/sum(N_sites)] / [[sum(SNV_S_count)/sum(S_sites)], how should the pNpS for the genome be calculated?

Best,
Na

**Comment by dzxiaona** [comment]
Your reply is very helpful to me. Thank you very much!

Best,
Na
