### ISSUE TITLE
Same concept with amplicons?

### ISSUE THREAD

**Issue by liamfitzstevens** [MrOlm/inStrain#149]
Hi Matt,

This is only thematically-related to inStrain. If you don't have the time to answer this, no worries; I would simply close out the issue. If you do:

Colleagues will be performing field amplicon sequencing, are looking for the best tool to identify amplicon SNVs, but they already have reference genomes. They will be looking for clonal, or close to clonal amplicons.

Do you know whether there are good tools to perform the same concept of inStrain (map, in this case, amplicon reads, to a reference genome to make profiles, and compare those profiles)? (I recommended they consider inStrain down the road, lest they end up doing metagenomics.)

Thanks and best,
Liam

**Comment by MrOlm** [comment]
Hi @liamfitzstevens - thanks for reaching out

I worry that the popANI concept might not be applicable in the case of amplicon sequencing due to how short the reads are and the fact that you're sequencing only universal genes. You might end up getting 100% popANI values reported if there's a single bacterial genome shared between the samples, which is probably not intended.

The only SNV-variant calling technique I can think of around this concept is oligotyping (https://merenlab.org/software/oligotyping/). I don't have personal experience with it but I'm a fan of Meren's work, so if I were your colleagues it's what I would try.

Sorry not more useful!

-Matt
