### ISSUE TITLE
Could not load the scaffold to bin file

### ISSUE THREAD

**Issue by morgvevans** [MrOlm/inStrain#15]
Hi, this is a fantastic tool! I have a question about the scaffold to bin file.
In the tutorial it says 'One is to give inStrain a list of the .fasta files that went into making the concatenated .fasta file. The other is to provide inStrain with a “scaffold to bin” file, which lists the genome assignment of each scaffold in a tab-delimited file.  In this case we’re going to use the scaffold to bin file provided by inStrain.."
I tried to supply a .txt file that has the universal location of the .fasta files present in the concatenated fasta as per your tutorial, space separated, but I keep getting the following error:

Could not load the scaffold to bin file!
Traceback (most recent call last):
  File "/users/PAS1331/osu7930/miniconda3/envs/instrain/bin/inStrain", line 31, in <module>
    inStrain.controller.Controller().main(args)
  File "/users/PAS1331/osu7930/miniconda3/envs/instrain/lib/python3.6/site-packages/inStrain/controller.py", line 35, in main
    self.profile_operation(args)
  File "/users/PAS1331/osu7930/miniconda3/envs/instrain/lib/python3.6/site-packages/inStrain/controller.py", line 61, in profile_operation
    ProfileController().main(args)
  File "/users/PAS1331/osu7930/miniconda3/envs/instrain/lib/python3.6/site-packages/inStrain/controller.py", line 224, in main
    Controller().genome_wide_operation(args)
  File "/users/PAS1331/osu7930/miniconda3/envs/instrain/lib/python3.6/site-packages/inStrain/controller.py", line 73, in genome_wide_operation
    inStrain.genomeUtilities.Controller().main(args)
  File "/users/PAS1331/osu7930/miniconda3/envs/instrain/lib/python3.6/site-packages/inStrain/genomeUtilities.py", line 468, in main
    stb = load_scaff2bin(args.stb, IS)
  File "/users/PAS1331/osu7930/miniconda3/envs/instrain/lib/python3.6/site-packages/inStrain/genomeUtilities.py", line 568, in load_scaff2bin
    assert False
AssertionError

My command:
inStrain profile bt2_peru_mapped/peru_drepbins_SRR2938072.sam peru_drepbins.fasta -o peru_drepbins_SRR2938072.IS -p 6 -s perubins_space.txt

I have a set of ~270 dereplicated MAGs from about 100 samples, and another set of ~270 MAGs from about 180 samples, so I'd prefer not to go through and grep the scaffolds from every MAG then match them to MAG ID -- I am sure there's an easier way to pull scaffolds from fasta and associate them with the bin ID w/ perl or something but I'm not super saavy in that arena. Am I just formatting my .txt file incorrectly or is there something I am missing that can solve this issue? Since the tutorial says inStrain provides the scaffold to bin file I was wondering if there is a way to generate it? I've included one of my fasta files that goes into the concat fasta file (I figured the concat file is too big to upload here) and then the list of fasta files in the concat fasta file. 
[debug.zip](https://github.com/MrOlm/inStrain/files/4738318/debug.zip)

Thanks!

**Comment by MrOlm** [comment]
Hi Morgan,

Thanks for the detailed bug report. I looked into this and think I identified the issue, and have a couple of possible solutions.

The problem is that the text of the tutorial is poorly written- it says that you can provide a list of the .fasta files that went in, but inStrain actually wants them as command line arguments. So, for example:

`inStrain profile bt2_peru_mapped/peru_drepbins_SRR2938072.sam peru_drepbins.fasta -o peru_drepbins_SRR2938072.IS -p 6 -s /path/to/genomes/*.fa /other/path/to/genomes/*.fasta`

Inputting the genomes that way should fix your problem- a way of doing this with the genome list you already have is:

`inStrain profile bt2_peru_mapped/peru_drepbins_SRR2938072.sam peru_drepbins.fasta -o peru_drepbins_SRR2938072.IS -p 6 -s $(cat perubins_space.txt | tr '\n' ' ')`

If this doesn't work or if you don't want to do this, the following tool can generate scaffold to bin files like you want:

https://github.com/MrOlm/drep/blob/master/helper_scripts/parse_stb.py

Running the command `pip install drep` should put parse_stb.py in your path, and you should be able to see the help (which has an example) with the command

`parse_stb.py -h`

Let me know if this problem persists!
-Matt

**Comment by morgvevans** [comment]
Great, thank you for the quick reply, will try this out now!

**Comment by morgvevans** [comment]
This worked, thank you very much!
