### ISSUE TITLE
warning FAILURE StbError

### ISSUE THREAD

**Issue by ramiroricardo** [MrOlm/inStrain#33]
Hi @MrOlm ,

I have started to use inStrain and thanks for developing such a great tool.

I have mapped reads with bowtie to a subset of the UHGG database, as described in the tutorial, but then I am only interested in one species and am using inStrain with only one reference genome. 

After using `inStrain profile`, I am getting multiple warnings such as this: 
`FAILURE StbError GUT_GENOME284629_65 GUT_GENOME284629.fna no_length will not be considered as part of the genome
`

Is this simply because my sam/bam files have been mapped against the UHGG, but then I have a single reference genome when using inStrain?

The code I used was:

```
bowtie2 -p 10 -X 2000 --no-mixed --very-sensitive \
  -x UHGG_reps_selected.fasta.bt2 \
  -1 cat_trimmed_1.fastq.gz \
  -2 cat_trimmed_2.fastq.gz > test.sam

inStrain profile test.sam reference.fna \
  -o test.IS -p 10 -g reference.genes.fna \
  -s reference.stb

```

the `reference.stb` only has the contigs for my genome of interest `reference.fna`.

Thanks for any help,

Ramiro

**Comment by MrOlm** [comment]
Hi Ramiro,

Thanks for the detailed bug report. That error happens when inStrain is unable to find a scaffold that's listed in the .stb in the .fasta file provided. So for example, inStrain thinks that the scaffold `GUT_GENOME284629_65` isn't in the file `reference.fna`.

If the scaffold is in there, I'd be happy to try and see what's going on. For debugging it'd be helpful to have the files ` reference.stb`, `reference.fna`, and `test.IS/raw_data/scaffold2length.json`

It's also worth noting that if you're only wanting to profile a single genome, you don't need to provide an `.stb` file. InStrain will automatically calculate genome-level metrics just based on the scaffolds in `reference.fna`. InStrain was definitely designed to be able to handle your use-case (mapping to a big .fasta and then profiling just a single genome in the resulting .bam), so this should work.

Best,
Matt

**Comment by nick-youngblut** [comment]
The `FAILURE StbError` sounds like an actual error instead of just a warning. Maybe change to `WARNING: StbError`?

I'm getting this warning when running `inStrain genome_wide` on the `inStrain compare` output, and so it appears that the `compare` output just doesn't include some of those contig IDs that are in the `*.stb` file. 


A small thing about the `inStrain genome_wide` cli doc: 

>   -i IS, --IS IS        an inStrain profile object (default: None)

Isn't the "object" really just the output directory of `compare`?

**Comment by ramiroricardo** [comment]
Hi Matt,

thanks for your quick reply. The genome I am using as reference has two contigs (genome + plasmid). Is it ok to still run `inStrain profile` without the `stb` file in this case or only for single contig genomes?

**Comment by MrOlm** [comment]
Hi @nick-youngblut - yeah you're right, warning would probably be more appropriate in this case. And yes, that is what getting that error in that circumstance means. Also thanks for pointing out the error with the cli doc- yes, the object should be the output of `compare`. I'll also point out that with inStrain v3+, the `genome_wide` module itself is being deprecated. The preferred way of doing things with v3 is just to provide your .stb file to the `inStrain compare` command, in which case it'll do all the genome_wide stuff that way. But doing things as you're running them (in two steps with `compare` and `genome_wide`) still works at the moment, it's just a bit slower.

@ramiroricardo - If you don't provide an .stb all genome-wide metrics will be calculated for the plasmid and the genome together (they'll be treated as the same entity). If that's what you want, running without the .stb is fine, but if you want to have separate info on each you should provide an .stb specifying the two genomes. Also, you can just provide a list of the two genomes to inStrain instead of the .stb if you'd like (`-s genome1.fasta genome2.fasta`). On the backend it'll just make an .stb from those genome genomes based on the scaffold headers in those .fasta files.

Best,
Matt
