### ISSUE TITLE
inStrain compare: inaccurate time reporting for tqdm

### ISSUE THREAD

**Issue by nick-youngblut** [MrOlm/inStrain#40]
I've noticed that tqdm isn't really accurate for the group-level processing. It usually quickly reaches `N-1/N` and then "stalls" for quite a while before finishing and moving onto the next group. Maybe it's taking a long time to close the processes:

```
    # Close multi-processing
    for proc in processes:
        proc.terminate()
```

As an example of non-accurate tqdm time reporting, this took ~5 hours:

```
Running group 27 of 148
Comparing scaffolds: 100%|██████████| 687/687 [15:16<00:00,  1.33s/it]
Running group 28 of 148
Comparing scaffolds:  85%|████████▌ | 1371/1608 [1:04:07<14:14,  3.60s/it]
```

Maybe putting it all in `tqdm.process_map()` will help?

**Comment by MrOlm** [comment]
Interesting- I knew this was a problem but didn't know `tqdm.process_map()` existed. I'll look into it and see if it's feasible to implement

**Comment by nick-youngblut** [comment]
`tqdm.process_map()` makes life easier. Maybe it will help in this case for providing more accurate time-to-completion info

**Comment by MrOlm** [comment]
I looked into this a bit, and I think the problem is just that some scaffolds take much longer to run than others.  The progress bar is being updated as soon as the results are ready `pbar.update(1)`, the problem is just that some scaffolds take a while to run (and these are the rate-limiting scaffolds).

`tqdm.process_map()` won't work in this cause because I'm not using the standard "map" feature to do the multiprocessing. I use to use `map`, but switched to manual control to help with RAM usage.

I think for now the progress bar should just be used to see how many scaffolds are remaining to process, not necessarily to predict how much longer the program has to run.
