### ISSUE TITLE
Question about filtering genomewidecompare

### ISSUE THREAD

**Issue by smb20200615** [MrOlm/inStrain#48]
Hello,

I had a question about filtering the genome wide compare tsv file. I am comparing highly similar metagenomes and I am getting very low percent_compared (<0.005). I was hoping to filter based on a percent_compared of 0.5 and ANI of 99.99%. I am worried that nothing will be left after I filter. Do you know how to make sense of this low percent_compared given that these samples are expected to contain similar strains? Could it be an issue with my dereplicated isolates? I dereplicated a set of isolates at 97% ANI to get this dereplicated set that was inputted to instrain.

Thank you as always,

Just as a side question, do you ever filter based on coverage_overlap?

**Comment by MrOlm** [comment]
Hello,

My guess is that coverage depth is just low. InStrain can only compare regions of the genome that are at at least 5x coverage (in order to sample the population-level diversity). You can tell what percent of the genome is present at 5x coverage by looking at the columns `breadth_minCov` in the table `genome_info.tsv`. You want that to be at least 0.5 in both samples being compared to perform a robust genome comparison (meaning at least 50% of the genome is coverage at >=5x coverage depth.

It's a good question about `coverage_overlap`, but I honestly haven't used that column much at all in my own research.

-Matt
