### ISSUE TITLE
Unexpected error at end of run; not reported in log file

### ISSUE THREAD

**Issue by kblock-due** [MrOlm/inStrain#49]
I ran the inStrain profile command resulting in this error (screenshot), which is not reported in the log file and the output is as expected.

The exact command I used:
`inStrain profile MoCom-vs-gtdb.sam gtdb.fasta -o MoCom -p 10 -g gtdb_genes/gtdb.gene.fna -s scaf2bin.tsv --database_mode`

What could cause this error?
Can I still use the output?

![Screenshot 2021-03-11 at 08 08 36](https://user-images.githubusercontent.com/80524905/110940383-1abd8500-8337-11eb-878b-6f95fc1dab64.png)

**Comment by MrOlm** [comment]
Hello,

This error happened while inStrain was creating the runtime report, a text document that summarizes runtime efficiency and how long certain steps took to run.  InStrain creates this report after closing the log, so any errors aren't saved in the log.

You can definitely still use the output. If you're comfortable sharing your log file (`logger.log`) I'd be happy to see what's causing the bug and fix it. Feel free to email it to me if you'd prefer as well.

Best,
Matt

**Comment by kblock-due** [comment]
Hello,

Thank you very much for your help and fast response.

I only have a log.log file as an output, which is attached to this email.
 log.log
<https://drive.google.com/file/d/1RFLtrenJPGbTtdb26PyfE5OOIAYtDR1R/view?usp=drive_web>
If there are any problems with the download, please let me know.

Thanks again,
Katharina

Am Fr., 12. März 2021 um 18:19 Uhr schrieb Matt Olm <
***@***.***>:

**Comment by MrOlm** [comment]
Thank you for sending over the log. I looked into this problem, and it results from the fact that some of your sequences have semi-colons in the header names (``;``). This interferes with the way the logs are parsed.

Fixing this issue turned out to be pretty complicated, so I decided not to pursue it. The log file made at the end is really only necessary for troubleshooting runtimes anyways.

If you really do want this log file for some reason, replacing the semi-colons with some other character in your fasta headers will do the trick.

Best,
Matt
