### ISSUE TITLE
Error plotting plotting

### ISSUE THREAD

**Issue by slaperriere** [MrOlm/inStrain#6]
Hello, 

I am getting the following errors when running instrain plot. 

For plotting plot 6: 
/home/shengwei/anaconda3/envs/InStrain/lib/python3.8/site-packages/inStrain/plottingUtilities.py:743: RuntimeWarning: invalid value encountered in double_scalars '{:1.0f}%'.format((width/total)*100),

And for plotting plot 7:
Failed to make plot #7: 'midpoint'

Do you know what the problem could be? Thank you!

**Comment by MrOlm** [comment]
Hi Slaperriere,

Apologies for the long response time. I know that the figures are a bit buggy at the moment, and do have an idea of what the problem is and how to fix it, but it's taking a bit more time than expected. Thank you for the bug report and I'll update this comment when I think I've fixed this figure bug.

Best,
Matt

**Comment by MrOlm** [comment]
Hi Slaperriere,

inStrain version 1.5.0 has major changes to how the plotting is done, and I believe these issues have now been fixed. Please let me know if the issue persists after upgrading versions.

Best,
Matt
