### ISSUE TITLE
genome-wide vs gene-sepecific pN/pS

### ISSUE THREAD

**Issue by Thexiyang** [MrOlm/inStrain#60]
Hi. Just check if the genome-wide pN/pS is the average of pN/pS of all genes in that genome. Thanks!

**Comment by MrOlm** [comment]
It's not quite the average of all genes, it's the sum of all SNVs across all genes. So it essentially treats all of the genes on the genome as one long gene, and then calculates the pN/pS of that long gene. Does that make sense?

-Matt

**Comment by Thexiyang** [comment]
Thanks. This parameter is not shown in the genome_info.tsv. Or do I miss it? Could you advise the equation to do calculation based on the SNV output?

**Comment by MrOlm** [comment]
Oh whoops- I thought that was automatically calculated.

It can be calculated using the file `genes_SNP_count.csv.gz` in the `raw_data` folder, and the file `gene_info.tsv` in the output folder.

`genes_SNP_count.csv.gz` has the values `S_sites` and `N_sites` for each gene. There's lots of other stuff in there too, but it's best to ignore it because it's on the mm level (if interested you can see what I mean here https://instrain.readthedocs.io/en/latest/advanced_use.html#dealing-with-mm)

For each genome that you'd like to calculate it for, subset `gene_info.tsv` to just genes from the genome of interest. Then add in `S_sites` and `N_sites` for each gene in the table. 

For dNdS_substitutions, use the formula:

[sum(SNS_N_count) / sum(N_sites)] / [[sum(SNS_S_count) / sum(S_sites)]

For pNpS_variants, use the formula:

[sum(SNV_N_count) / sum(N_sites)] / [[sum(SNV_S_count) / sum(S_sites)]

Sorry for the confusion. I will also have this value reported in `genome_info.tsv` in future versions of inStrain.

Best,
Matt

**Comment by Thexiyang** [comment]
Thanks! One more question on the r/m. I did not find r/m values in the inStrain output. In the soil paper, it said: "The relative rate of recombination to mutation (gamma/mu) for each population was calculated using the mcorr package (cite) on synonymous third position codon sites across filtered mapped reads from all samples. " This is not clear to me. Could you provide some further guidance to calculate this parameter based on output from inStrain?

**Comment by MrOlm** [comment]
@alexcritschristoph

**Comment by alexcritschristoph** [comment]
Hello, 
The gamma/mu calculation in that paper was performed with the mcorr package:
https://github.com/kussell-lab/mcorr
Which is an independent pipeline from inStrain. That probably clears this up!
