### ISSUE TITLE
Issue with Paired End Reads from SRA

### ISSUE THREAD

**Issue by elizabethmcd** [MrOlm/inStrain#63]
I've downloaded some metagenomes from SRA and mapping to MAGs. I'm getting an error that %nan reads were filtered because there aren't paired end reads. I'm mapping with bowtie2 and from the log it appears they are mapping in pairs, and from the SAM file it looks like they are in pairs. The only difference that I can find is how SRA arbitrarily renames read pairs compared to how PE files are named by Illumina. The SRA reads are named like: 
```
SRR11673976.4456606.1
SRR11673976.4456606.2
```
Whereas PE reads directly off a HiSeq run appear in the SAM file with the same name, such as `HISEQ09:132:C61LEANXX:6:2316:20607:101411`. I've had issues before where programs don't like how SRA names paired end reads, but bowtie seems to handle it fine in this case. Should I change the read names before mapping or is there a way to have inStrain recognize this? And as a general/random aside - do you have recommendations for renaming read pairs from SRA? I've tried the `repair.sh` and `reformat.sh` in the BBMAP tools with little success and feel like there should be a better way.

**Comment by MrOlm** [comment]
Hello,

A couple of things. 1) InStrain detects pairs reads using pysam (samtools), and it considers paired reads those that have the same "query_name". So in this case it does seem like that could be the problem for you. Thats really a bummer that the SRA renames reads in this way- I haven't encountered this problem before. 2) You could always just ignore the paired-read filter within inStrain if renaming reads turns out to be a pain (`--pairing_filter all_reads`). 3) I've used `reformat.sh` to ensure reads are paired, etc., but I've never renamed reads in the way you're describing. 

Best,
Matt
