### ISSUE TITLE
`instrain profile`: 15 hours and counting

### ISSUE THREAD

**Issue by liamfitzstevens** [MrOlm/inStrain#68]
Hi Matt,

The "Important Concepts" documentation states in heading 2, subsection 4b that "... for a number of reasons 95% ANI is a good minimum ANI threshold for establishing genome databases." You used SSRGs (dRep, 98%) to identify strain-sharing events in your January _Nat. Biotech._ paper - as the documentation states, this affords more granular comparisons. With a similar goal of identifying strain-sharing events in different hosts, I’d like to use SSRGs too.

I'm running a test of `instrain profile` on my institute server with 2 metagenomes (~3mil reads) and all project SSRGs (>3000). About 12 hours in, it was on step 4 ("Make genome-wide"), and at hour 15 it's on step 5 ("Generate plots"). It's great that it's running error-free, but this timing is an issue given that I'd like to run this on the entire dataset (~800 metagenomes). That’s before even taking `instrain compare` into account, which will also presumably take very long.

One option would be to run the metagenomes with the project SRGs (dRep, 95%), of which there are far fewer (<1000). The aforementioned documentation suggests that this wouldn’t be an issue: would you suggest I use that approach here? It may be the only way to run inStrain on the entire dataset, but do you think I might loose strain-sharing signal that SSRGs would have been able to identify?

Best regards,
Liam

**Comment by MrOlm** [comment]
Hi Liam- great question. A couple of things. 

1) I think running with 95% is fine for most things. In a study I'm working on that's in it's final stages I used a 95% dereplication to save on compute time, and the strain sharing results I got were great. So I think switching to that is a perfectly fine option. My intuition is that it'll only impact things on the margins, but I haven't done a lot of testing in that regard.

2) That's a long time. When I run inStrain profile I use the modifiers `--skip_plot_generation` and `--database_mode`. `--database_mode` is especially important for speeding up runtime. But if you're already using those options, I guess it just is what it is. You an always look at the `runtime_log.txt` (I forget the exact name but it's something like that) in the `log` folder produced at the end of the run to see where it's spending all it's time at least. If there's some huge bottleneck it would be nice to know where it is.

3) InStrain compare is really fast for individual comparisons, but it's done in a pair-wise manner, so it takes a long time when you have lots of samples with the same genome that you want to compare. Comparing a genome present in 5 samples is very fast, 20 samples is still pretty quick, but when you get over 80 samples or so is when it starts taking a long while. I've done up to ~120 samples and that take a few days to run. Even if a genome is present in 100 samples, if you only care about strain sharing within dyads / between certain samples / ect., you can run inStrain compare in multiple groups to reduce the pair-wise scaling complexity.

Best,
Matt

**Comment by liamfitzstevens** [comment]
Thanks Matt! I implemented the first two recommendations, and will keep the third in mind if it's later indicated (i.e., if `inStrain compare` takes too long).

1. Would you recommend running `inStrain compare` with `--skip_plot_generation` and `--database_mode` too (same big dataset)?

2. `inStrain profile` could run with the two aforementioned modifiers only when I switched my `Snakefile`'s `RDJ` output from `Rdic.json` to `Rdic.pickle`. Is a requirement for inStrain users globally? I can add an `if` statement to our lab's pipeline to solve this technicality for future users of your software in my lab, but if it can be resolved on your end, that might be worth considering. I anticipate I'll need to do the same for `inStrain compare`.

**Comment by MrOlm** [comment]
Hello,

1) With inStrain compare, `--database_mode` alters the program functionality in ways that don't necessarily increase speed. There are a couple of ways of running inStrain compare depending on your goals (e.g. you can run it one genome at a time, with only certain samples, etc.). Running inStrain comapre in `--database_mode` will essentially make it compare as many genomes as it can between all the input samples. If that's your desired output, great, but it won't change runtime too much. Similarly the plots made by compare don't take a long, so `--skip_plot_generation` won't impact runtime very much either. With inStrian compare, really the only thing that impacts runtime is the amount of samples you give it compare, since because it has to run pair-wise comparisons there's an exponential increase in runtime.

2) I'm not very familiar with Snakemake or RDJ output and don't quite understand your question; could you perhaps rephrase it?

Thanks,
Matt

**Comment by liamfitzstevens** [comment]
Hi Matt,

Thank you for the feedback and ideas. Running inStrain compare with `--database_mode` makes the most sense for this application: comparing as many genomes as possible. Great to know that these modifiers reduce runtime most significantly for `profile`.

No worries about the Snakemake issue, as it appears it's only pertaining to our lab's implementation of the software on our compute infrastructure. I'm new to Snakemake myself, but for whatever reason, when using the `--database_mode` modifier for `profile`, the `per-sample/{sample}/raw_data/Rdic.json` output had to be switched to `.pickle` in order for it to run. It's working after having implemented this change.

Thanks again!

Best,
Liam

**Comment by liamfitzstevens** [comment]
Hi Matt,

Brief follow-up:

Have you since benchmarked how using SRGs (95%) v. SSRGs (98%) affects inStrain's sensitivity? We used the former for our recent paper but are proceeding with the latter for our current project as it should be more sensitive; just wondering if that difference has been quantified.

Best,
Liam

**Comment by MrOlm** [comment]
Hi Liam,

I have done a little bit of testing this myself, but I have not done a comprehensive benchmark. It is something that has been on my "To Do" list for a long time.

With 98% you do detect more genomes (I personally refer to each genome as a "sub-species" at this threshold), but there are a small fraction of genomes that ARE detected at 95% and ARE NOT detected at 98%. This happens when there are many 98% genomes that split reads between them, meaning no individual genome gets to 50% breadth, but when mapping to a 95% genome the reads all map to the same species-level genome you detect that genome.

This issue seems to effect some species way more than others, likely due to something biological about how they maintain their pangenomes, but like I said I haven't fully investigated this.  

Hope this helps,
Matt
