### ISSUE TITLE
genome coverage 

### ISSUE THREAD

**Issue by Thexiyang** [MrOlm/inStrain#69]
Hi. 

I am wondering the minimum genome coverage requirement for inStrain. The inStrain outputs the results for all genomes, even if the genome coverage is below 5 at one sample (based on `inStrain quickprofile`). Does it mean that we can use all these population genetics results for data interpretation?  Or should I need to filter out the genomes with very fewer coverage (e.g. <5) at one sample?

Also related to this, I noticed that in the  command-line arguments for inStrain profile, there are both `-c MIN_COV` (default 5) and `--min_genome_coverage` (default 0). What are their differences? 

In the NBT paper for this software, it says: We chose 5× as the default minimum because it is the lowest coverage at which minor alleles under 50% frequency can be reliably detected (Supplementary Fig. 2)... What does this 5 mean? Is it the minimum coverage for gene or genome?

Additionally, I found that the coverage values in the output from `inStrain profile` and `inStrain quickprofile` are quite different. For `inStrain profile`, I used coverage values in the genome_info file. Which one I should choose to use?

Thanks!

**Comment by MrOlm** [comment]
Hello,

Lots of great questions- answered below:

1) The minimum coverage threshold depends on the analysis you intend to do. For population genomic analysis (analysis of intra-population diversity), 5x is the absolute minimum, but 10x is probably a better minimum. Higher coverage just means a higher ability to detect bi-allelic variants. A variant at 20% of the population will not be detected at 5x coverage, but will be at 10x coverage. For determining genome presence and absence, I like to use other metrics than coverage. See here for my thoughts on the problem - https://instrain.readthedocs.io/en/latest/important_concepts.html#detecting-organisms-in-metagenomic-data

2) `--min_genome_coverage` is only applicable when running in database_mode. All genomes below that threshold will be excludes from all analyses after read filtering in order to reduce program runtime. `MIN_COV` is the minimum number of reads needed for the program to look for SNVs

3) This refers to the `MIN_COV` parameter- the minimum coverage for inStrain to try and identify variants at a particular position

4) The difference between `profile` and `quick_profile` is that with `profile`, a number of steps are taken to filter mis-mapped or suspicious reads from the mapping file before profiling the genomes. You can look into plot 6 and/or `mapping_info.tsv` to see why you have reads being filtered out with `profile`, which would explain why the two are giving different values.

Best,
MO
