### ISSUE TITLE
Question about inStrain compare dendrograms

### ISSUE THREAD

**Issue by jmartin77777** [MrOlm/inStrain#71]
I apologize if this is explained somewhere in the documentation that I missed, but what do the label colors mean in the inStrain compare dendrogram? The branch colors make sense, and seem to be based around an ANI value split.  But I can't figure out what the label colors are telling me.

**Comment by MrOlm** [comment]
Apologies for how confusing the color scheme is and for having no documentation about it- I'll add docs soon.

Colors are assigned based on 99.9% ANI in the left plot. The same color scheme in the left plot is then propagated to the right plot.

-MO

**Comment by jmartin77777** [comment]
Cool, that makes sense for the branch colors.  But the samplenames listed in the plot also seem to have a meaningful color scheme but I can't figure out how they are grouped.  I have 128 samples in my plot and some of the denser clustering has many colors, moreso than there are branch colors.  I've screen captured one of the plots and attached it here.  Can you tell me what the samplename label colors mean?
![CompareDendrogramExample](https://user-images.githubusercontent.com/30535291/121043685-781c7300-c77a-11eb-8eb3-e970774ab5d0.png)

**Comment by MrOlm** [comment]
Hello,

So the branch colors are actually arbitrary (I don't set them, they're set automatically by matplotlib), and the label colors follow the scheme I described above. Some confusion may be caused by the fact that the colors set set using `single` hierarchical clustering, which can give odd results' and the fact that the colors are chosen in a funny way such that nearly identical colors can be chosen for distinct groups.

The coloring is not well thought out for inStrian, though, and is a holdover from code I wrote for another program. I will try and fix the coloring / document it better / make it useful in future versions of inStrain.

-MO

**Comment by jmartin77777** [comment]
Ah, sorry for my misunderstanding!   That does make sense now, and I like the idea that I would be able to see those 99.9% ANI groupings at a glance.  The similar colors are confusing at first but make more sense when you look at it in combination with the clustering.   Thanks!
