### ISSUE TITLE
Question about metagenomic SNP-calling

### ISSUE THREAD

**Issue by KingsRoad** [MrOlm/inStrain#73]
Hello,

Sorry for bothering the authors through E-mail just now, I didn't realize that I should directly post the issue in github~

Our group is working on the SNP calling in metagenomic sequencing data, and we recently also published a benchmark paper about performance of different SNP calling tools (https://www.frontiersin.org/articles/10.3389/fgene.2021.648229/full), inStrain is one of the benchmarked tools. We found inStrain is very powerful with diverse functions and easy to use, therefore we decided to use inStrain to call metagenomic SNPs in our own cohort (Lifelines-DEEP, N=1,135). We firstly chose only two reference bacterial genomes for testing, and the ‘profile’ step was very fast, and it only took <1 day to profiling all samples. However, the second step ‘compare’ was very slow and memory-consuming with the parameter ‘--store_mismatch_locations’, we can’t run all the samples together in the same batch, do you have a solution for this situation?

We use the parameter ‘--store_mismatch_locations’ because we want to conduct a kind of ‘joint calling’, to provide the genotype (or allele frequency) of all SNPs in the cohort for all samples. If you have an alternative way to do this efficiently, that will be super helpful! 

Thank you very much!

**Comment by MrOlm** [comment]
Hi Daoming,

Thanks for posting your question publicly on GitHub so that others with the same question can potentially find it! And also thank you and your labs work comparing metagenomic SNP calling tools; we read your manuscript with great interest and think unbiased comparisons like yours are really helpful to the field.

I understand your question, and support for joint SNP calling is near the top of our development "To Do" list for inStrain, but unfortunately there isn't a great way to handle your request at the moment. `--store_mismatch_locations` stores information in a pair-wise manner, and because of this the RAM use increases exponentially with increasing sample number (leading to the effect you're seeing). This is also true for pair-wise comparisons; comparing more than 80 samples or so of a genome will start taking a lot of computational time. We're working on improvements to both of these (storing SNP compare information in a more RAM-efficient manner and adding support for greedy strain clustering to avoid pairwise comparisons), but those improvements won't be ready in the near future.

For now some options are 1) break up your 1135 samples into specifically interesting groups. For example in research looking at vertical transmission of strains from mothers to infants, rather than running all samples together, you could consider running each mother / infant pair as it's own inStrain compare run. This will of course drastically reduce the number of pair-wise comparisons performed.

2) Use the SNVs.tsv info from inStrain compare rather than using the compare module. The only caveat here is that coverage is not included. For example, consider a SNP in sample 1 that's not in sample 2. When just looking at SNVs.tsv, you can't know if the SNP is not in sample 2 because that position has no coverage, or if the reads in the sample genuinely don't have a SNP in them. InStrain compare only compares SNPs at positions that have coverage in both genomes.

3) Co-developer @alexcritschristoph has some hacky scripts that can approximate the feature you're asking for, but be warned that they're not pretty to use. I'm sure he'd be willing to share if you're interested.

Thanks for reaching out, let me know if you hit any other snags, and I'll let you know when the new SNP features are ready and part of the codebase

-Matt
