### ISSUE TITLE
dRep 99% vs InStrain for pangenome analysis

### ISSUE THREAD

**Issue by adriaaula** [MrOlm/inStrain#78]
Hello Matt,
 
We have done metagenomes for 3 experiments in which we want to compare the species at the strain level.
From every single assembly, I have obtained mapped the sample, obtained the bins and I am now applying `dRep` to the whole dataset.
 
I have a question regarding which is the best way to proceed. My objective is to obtain the pangenome and strain differentiation for a specific set of species.
 
- Apply `dRep` for a 99% ANI differentiation. From that, I would obtain strain level MAGs, map again all the samples, and obtain the abundance patterns for each strain separately. The reads that match 100% would be decided at random by bowtie.
- Apply `dRep` for a 95% ANI differentiation. Map all the reads back. Apply `inStrain` to that representative species set to observe the strain representation.
 
My question is: If I use (2), what happens if for `dRep` the representative genome X is strain X but this strain does not present a specific gene only present in strain Y? Is this usual? My intuition says that by applying (1) this situation would be avoided since with the 99% ANI I would get the two strains to differentiate and I could apply pangenome techniques to them.
 
I saw that inStrain presents more resolution, but I don’t know how I should approach this.
 
Thank you in advance!

**Comment by MrOlm** [comment]
Hello,

Thanks for the excellent question. You've identified a really major split in potential ways of doing metagenomic analyses. I'm not sure if there's a really "correct" answer to this, but I can give you my thoughts on this issue.

I don't have much hard data to support this, but in my experience mapping back to 99% ANI dereplicated genomes doesn't go very well. In a couple of different datasets I've done both a 99%/98% ANI dereplication and a 95% ANI dereplication and compared what I see. I use a 50% breath threshold to determine genome presence / absence (https://instrain.readthedocs.io/en/latest/important_concepts.html#detecting-organisms-in-metagenomic-data).  With 99% ANI I often see species not detected at all, but which ARE detected in the 95% drep data. This is usually the case when you have lots of genomes from the same species. I'll see a genome detected at ~20x coverage in the 95% drep data, and in the 99% drep data I'll see 50 strains from the species detected at 1x coverage each, but none of the 50 strains make it to the 50% breadth threshold. This is usually due to bowtie splitting reads that map equally well to multiple places (as you suggest) (https://instrain.readthedocs.io/en/latest/important_concepts.html#establishing-and-evaluating-genome-databases). I also see some cases where a species is detected in the 99% data but not detected in the 95% data (probably because the 99% genome is a better fit for the reads in the sample), but in my experience this is far less common than the other way around.

You're intuition about detecting more genes with 99% drep than 95% drep is also almost certainly true. When you pick a species representitive genome, it almost certainly will not have all the genes of all the other genomes in the representive genome. And all of the genes in those genomes that are not in the representitive genome will not be detected with mapping. 

My way of handling this has been to perform pangenome analysis and species / strain detection analysis separately. For pangenome analysis, I use the genomes themselves and a tool like Roary to cluster all the genes and identify which are core / shell / etc. within a 95% ANI cluster. I'll run Pfams / other annotations on those genes, and do a gene based analysis that way without mapping at all. I have also tried mapping to a pangenome of genes (the genes themselves, not genomes) and it works OK. The problem is that the genes are so small that a large portion of the reads go off the edges of the genes, and you can't really use paired-read information.

For species and strain analysis I'll do a 95% drep, map to representitive genomes, and track strains with inStrain. This mapping-based strain detection is far more sensitive than dRep can get, and the resulting species-level data you get for each sample is easy to work with and interpret (abundance / population genomics / iRep / SNV / linkage / etc.). You can also link back interesting species identified in this way to the pangenome info discussed in the previous paragraph.

Sorry for the wall of text and for not having an easy answer! Let me know if you have any more questions or if you make any discoveries about how to make this analysis work better. I don't love my solution (described above) because the two analysis are "unlinked" in some sense, but it's the best and most reliable method I've come up with so far. 

Best,
Matt

**Comment by adriaaula** [comment]
Hi Matt,
 
Sorry for the late response and thanks a lot for the thorough explanation.
 
Regarding this part:
 
> My way of handling this has been to perform pangenome analysis and species / strain detection analysis separately. For pangenome analysis, I use the genomes themselves and a tool like Roary to cluster all the genes and identify which are core / shell / etc. within a 95% ANI cluster. I’ll run Pfams / other annotations on those genes, and do a gene based analysis that way without mapping at all. I have also tried mapping to a pangenome of genes (the genes themselves, not genomes) and it works OK. The problem is that the genes are so small that a large portion of the reads go off the edges of the genes, and you can’t really use paired-read information.


From my dataset I have then multiple genomes and what you are saying is that in this is to not dereplicate them, and from the selected bins of interest I want to obtain the pangenome, I would do the following:
 
- Select the bins with the taxonomic assignation.

- Clean them somehow with anvio.

- Use them as an input to Roary.

- Voilà.

 
If what I said is right, to link the `inStrain` result with the pangenome you use specifically something, or usually, it is clear. Meaning: for a specific sample, I see in the `inStrain` result that one of the species outnumbers the other, and therefore in the pangenome it will be reflected, so I can trace which genome is obtaining this pattern.
 
Thanks a ton for everything!

**Comment by MrOlm** [comment]
Hello,

When I perform this analysis it's usually relatively "unlinked". For the inStrain part of the analysis, for example, I might say "E. coli is more abundant in population 1 than population 2, E. coli is growing faster in population 2, etc.). For the pan genome part of the analysis, I might say "E. coli has more antibiotic resistance genes in population 1, E. coli has more flagella genes in population 2", etc. So the "linking" is just based on organism taxonomy.

Best,
Matt
