### ISSUE TITLE
Could not find scaffold

### ISSUE THREAD

**Issue by elizabethmcd** [MrOlm/inStrain#8]
I mostly use BBMap for most of my mapping needs. When I passed the BAM/SAM files to InStrain, I got errors about scaffolds couldn't be found and there weren't any reads in said scaffolds. This was resolved when I followed the tutorial and used Bowtie2 instead. I believe the error comes from the scaffold ID not being in the same column when BBMap outputs the BAM/SAM files, as I've had similar problems with how BBMAp outputs things and then using for other downstream programs. This is no longer an issue for me (since I switched to Bowtie2) - but I would maybe add a disclaimer to use a certain mapping software or to reformat the BAM/SAM files in a certain order than InStrain can take in, so future users know of this.

**Comment by MrOlm** [comment]
Hi Elizabeth,

Thank you for posting this- it's a good idea for me to maintain a list of mapping software that is confirmed to work with inStrain. I'll first see if it's possible for me to make BBMap work with inStrain, though it might not be possible if the problem is with pysam and the .sam file format specification itself, and either way work towards logging this information in the documentation.

Best,
Matt

**Comment by MrOlm** [comment]
FYI- as of version `1.2.4` it is possible to use BBMap with the flag `--use_full_fasta_header`. The problem is that BBMap uses the scaffold description (every after `>`) rather than the scaffold ID (everything between `>` and the first space).

Still need to add documentation for supported mappers, though

**Comment by MrOlm** [comment]
Added to upcoming docs release
