### ISSUE TITLE
Insights regarding nucleotide diversity

### ISSUE THREAD

**Issue by adriaaula** [MrOlm/inStrain#85]
Hello there :^)
I have obtained the nucleotide diversity pattern for multiple MAGs and I wanted to compare the distribution at the t0 of an experiment and at the final time. I have used the `genome_wide_info.tsv` for obtaining the nucleotide diversity values. The values come from de novo marine assembled genomes dereplicated at 95% identity.
The values however differ a lot between the standard nuc. div. and the nuc div. rarefied version.

Without rarefying:

![image](https://user-images.githubusercontent.com/15213478/135446829-6f869a27-0126-4b88-af3d-f3627f92bcdb.png)

Rarefying: 

![image](https://user-images.githubusercontent.com/15213478/135446891-4fc71b21-855e-4ab3-9961-bbcdaede5347.png)

Given the differences between the two methods, I thought that in some cases there is non-specific mapping in a region of the genome, which raises the nucleotide diversity values artificially. Could that be possible? Since the nucl_div_rarefied is taking into account only the positions with 50X genome coverage I thought that would be an explanation. I was trying to be conservative by using the rarefied version but I think I mistook the measurement for something else. Since these are marine metaG with a lot of diversity I guess 50X cov is too stringent?

I also do not quite understand how do the popANI is related with the nucleotide diversity measurement.  I would expect that the higher the nucleotide diversity, the lower the popANI. In most cases I see this pattern but for the MAGs I am putting here the pattern seems to be inverse. Thoughts?

![image](https://user-images.githubusercontent.com/15213478/135447041-ac4aa246-089c-4af4-a0c6-92042207a013.png)

Thanks a ton for the tool :)

**Comment by MrOlm** [comment]
Hi @adriaaula,

Thanks for the question. I have some insight here, but I must say that I still don't understand all of the output always either. I believe the data that inStrain reports is correct, and I understand how all the calculations are done, but biological interpretation can still get a bit tricky. I'm thrilled that you're using the tool to understand ocean microbes and I can't wait to read about the insights you find! I'll also tag @alexcritschristoph here, the co-author of inStrain, to see if he has any added insight.

Nucleotide diversity can be impacted by 1) genuine diversity, 2) read mis-mapping, and 3) the base error rate of the sequencing technology used. Sequencing a fully clonal population would result in a nucleotide diversity that approached the error rate of the sequencer used (but this really only matters in practice if your study uses multiple different sequencing machines). Also, to get accurate nucleotide diversity levels you need very deep coverage (~300x maybe). I tend to not be a fan of the rarefied nucleotide diversity for this reason; it's simply less accurate because it has less data to go on (it ends up being 0-inflated).

In terms of mis-mapping, that's always a possibility. One way to check for that would be see if there are regions of the genome with high nucleotide diversity + higher coverage; that's a pretty strong signal of mis-mapping.

In terms of popANI, the main difference is that popANI only considers variants that rise above the background sequencing error rate. Whereas sequencing a clonal population would not give a nucleotide diversity of 1 (due to Illumina error rate), it would give a popANI of 1. Overall popANI is a less sensitive, more robust way of measuring genome-wide population diversity in my opinion. Also maybe a plot with popANI on the x-axis and nucleotide diversity on the y-axis would help explain what's going on?

Sorry for the rambling, but let me know if you have any other questions!
-Matt

**Comment by adriaaula** [comment]
Thank you for the fast response. 

Everything you said makes sense, thanks! 


Based in what you are saying I will stick to the popANI measures, which are more conservative and robust, and since I care mostly to solve 'are there strains for this MAG' it is good to go. Thanks for the tips. Right now I am finishing a draft of a paper and I won't have time to explore a lot but I promise I will look into it :)
