### ISSUE TITLE
Read trimming

### ISSUE THREAD

**Issue by andrewjmc** [MrOlm/inStrain#91]
Hello,

I have been typically relaxed about trimming reads based on quality for use with quality aware tools like bowtie, etc.

However, it appears that inStrain does not take base quality into account for calling variants. I'm therefore assuming read trimming is strongly recommended (or else I imagine low confidence bases at the ends of quality reads could cause spurious variants), and wonder if you have a suggested approach?

Thanks,

Andrew

**Comment by andrewjmc** [comment]
Just to add that I reran a sample for a specified set of genomes and it appeared to make little difference whether I used the trimmed or untrimmed reads. With trimmed reads, coverage depth fell from 7.6 to 7.4, nucleotide diversity rose from 0.0081 to 0.0082. ConANI fell from 0.980 to 0.979, and divergent loci increased from 22443 to 22550. So the small difference I have seen has increased diversity rather than reducing it (which would have been my concern).

**Comment by alexcritschristoph** [comment]
Hi Andrew, 
I believe instrain just calls SNVs with bases that have > phred30 quality scores. However I would recommend trimming beforehand as well. Interesting that diversity increased slightly. I think this would be because reads that had been excluded by percent ID to the reference due to some low quality base pairs now being included when those base pairs are trimmed.
